export default {
  type: 'object',
  properties: {
    firstName: { type: 'string' },
    lastName: { type: 'string' },
    age: { type: 'number' },
    phoneNumber: { type: 'string' },
    email: { type: 'string', format: 'email' },
    school: { type: 'string' },
    levelOfStudy: { type: 'string' },
    countryOfResidence: { type: 'string' },
    linkedInUrl: { type: 'string', format: 'uri' },
    mlh_code_of_conduct: { type: 'boolean' },
    mlh_privacy_policy: { type: 'boolean' },
    mlh_terms_and_conditions: { type: 'boolean' },
  },
  required: [
    'firstName',
    'lastName',
    'age',
    'phoneNumber',
    'email',
    'school',
    'levelOfStudy',
    'countryOfResidence',
    'mlh_code_of_conduct',
    'mlh_privacy_policy',
    'mlh_terms_and_conditions',
  ],
} as const;
